# Onyx 3D graphics configuration

# Notes on spatial orientation.
# We use OpenGL-style (right-handed) space:
#   X is left (-) right (+)
#   Y is down (-) up (+)
#   Z is forward (-) backward (+)
# The highway is flat, parallel to the Z axis,
# where future events come from the negative Z direction.
# The camera is positioned above the track,
# pointed at an angle towards that negative Z direction, then slightly down.

view:
  background: '#1c1d2b'
  # Y-bounds within highway view (0 = bottom, 1 = top)
  # where the track alpha fades off
  track-fade:
    bottom: 0.7734724292101341
    top: 0.8315946348733234
  # space will be split to give each track area close to this ratio
  height-width-ratio: 1.1666666666
  camera:
    position:
      'x': 0
      'y': 1.4
      'z': 3
    rotate: 25 # degrees down (around the X axis)
    fov: 45 # degrees
    near: 0.1
    far: 100
  # antialiasing options
  msaa: 4 # set to null or a number (probably one of 2, 4, 8, 16)
  fxaa: true # true or false

track:
  'y': -1 # height of the main notes area's floor
  # the width of the track available for notes (between railings)
  note-area:
    x-left: -1
    x-right: 1
  time:
    z-past: 2 # a point behind the camera's view, objects despawn at this time
    z-now: 0
    z-future: -12 # point where objects spawn
    # events this many seconds in the future will be at z-future
    secs-future: 1
  color:
    normal: '#333333'
    solo: '#333399'
  railings:
    color: '#737373'
    x-width: 0.09 # extending left/right from track
    y-top: -0.85
    y-bottom: -1.1
  beats:
    # height of the flat beatline images drawn on the track
    z-past: 0.05
    z-future: -0.05
  targets:
    z-past: 0.13
    z-future: -0.13
    # time the "light up" overlay takes to fade after a hit
    secs-light: 0.1666666
  # light used for the track itself (but not the gems on top)
  light:
    position:
      'x': 0
      'y': -0.5
      'z': 0.5
    ambient: '#333333'
    diffuse: '#FFFFFF'
    specular: '#FFFFFF'

objects:
  gems:
    # gems turn this color after being hit
    color-hit: '#FFFFFF'
    # gems take this long to fade away after being hit
    secs-fade: 0.1
    light:
      # relative to bottom center of the gem
      position:
        'x': 0
        'y': 1
        'z': 0.2
      ambient: '#333333'
      diffuse: '#FFFFFF'
      specular: '#FFFFFF'
  sustains:
    colors:
      open: '#c36ef4'
      green: '#4bfc5a'
      red: '#f45f5d'
      yellow: '#f4e05d'
      blue: '#7a74f7'
      orange: '#f4b153'
      energy: '#6cf7c6'
    # X span, centered in fret area
    width:
      open: 0.8
      fret: 0.2
    # Y distance raised off the track floor
    height: 0.02
